#
# Perform long-read adapter trimming using Porechop.
#

# Makefile preamble.
SHELL := bash
.DELETE_ON_ERROR:
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += --warn-undefined-variables --no-print-directory

# Micromamba environment.
ENV = bf-qc-porechop

# Run command within environment.
ENV_RUN = micromamba run -n $(ENV)

# Read file to process.
FQ ?=

# Output directory to store .
OUT ?= $(if ${FQ}, $(shell dirname ${FQ}))

# Trimmed FASTQ file.
TRIMMED = ${OUT}/trimmed_$(notdir ${FQ})

# Number of worker threads.
THREADS ?= 4

name:
	$(basename ${FQ})
	$(dir ${FQ})
	$(notdir ${FQ})

# Display usage.
help::
	@echo ""
	@echo "porechop.mk: trim adapters from long reads"
	@echo ""
	@echo "Usage:"
	@echo "  bf-porechop FQ=<FQ> [options]"
	@echo ""
	@echo "Commands:"
	@echo "  run            trim adapters from long-reads"
	@echo "  trim           an alias for 'run'"
	@echo "  install        initialize conda environment"
	@echo "  clean          remove all output generated by this program"
	@echo ""
	@echo "Options:"
	@echo "  FQ             a directory path containing the target reads"
	@echo "  OUT            a directory path for storing reports (default: .)"
	@echo "  THREADS        number of worker threads to use (default: 4)"
	@echo ""

# Fastqc options.
porechop_opts ?= -v 2 -t ${THREADS} --discard_middle

# Input FASTQ file must exist.
${FQ}:
	echo "Error: FASTQ file not found (FQ=${FQ})"
	exit -1

# Run porechop.
${TRIMMED}: ${FQ}
	# Create directory for trimmed reads.
	mkdir -p $(dir $@)

	# Trim reads.
	${ENV_RUN} porechop ${porechop_opts} -i ${FQ} > $@

# Invoke porechop.
run: ${TRIMMED}
	@ls -lh ${TRIMMED}

# An alias for 'run'.
trim: run

# Remove generated reports.
run!:
	rm -rf ${TRIMMED}

# An alias for 'run!'.
clean: run!

# Run test suite.
test::
	make -f $${BIOFLOW}/src/fetch/sra.mk SRR=SRR8848097 N=1000 MODE=SE run
	make -f $${BIOFLOW}/src/qc/porechop.mk FQ=reads/SRR8848097.fastq run! run

DEPS := porechop
# Command for installing dependencies.
install::
	micromamba create -n ${ENV}
	${ENV_RUN} micromamba install ${DEPS} --yes

# Rules without target files.
.PHONY: help run run! clean test install
