#
# Assemble reads into contigs using minia.
#

# Makefile preamble.
SHELL := bash
.DELETE_ON_ERROR:
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += --warn-undefined-variables --no-print-directory

# Micromamba environment.
ENV = bf-assembly-minia

# Run command within environment.
ENV_RUN = micromamba run -n ${ENV}

# Number of worker threads.
THREADS ?= 8

# Minia only accepts a single FASTQ file.
R1 ?=

# Basename of FASTQ file.
BASENAME = $(basename ${R1})

# Output directory.
OUTDIR ?= minia

# Target output.
CONTIGS = ${OUTDIR}/contigs.fa

# K-mer size(s).
K ?= 31

# Minia options.
FLAGS := -nb-cores ${THREADS} -kmer-size ${K}

# Compose minia command.
MINIA_CMD = minia ${FLAGS} -in ${R1} -out-dir ${OUTDIR}


help::
	@echo ""
	@echo "minia.mk: assemble reads into contigs using megahit"
	@echo ""
	@echo "Usage:"
	@echo "  bf-minia R1=<R1> [options] <command>"
	@echo ""
	@echo "Commands:"
	@echo "  run            assemble reads using minia"
	@echo "  assemble       alias for 'run'"
	@echo "  stats          compute contig statistics"
	@echo "  install        initialize conda environment"
	@echo "  clean          remove all output generated by this program"
	@echo ""
	@echo "Options:"
	@echo "  R1             a read file in FASTQ format (required)"
	@echo "  K              k-mer size (default: 31)"
	@echo "  OUT            a directory path for storing minia output (default: minia)"
	@echo "  THREADS        number of compute threads (default: 8)"
	@echo ""

# R1 must exist.
${R1}:
	@echo "Error: R1 not found (R1=${R1})"
	@exit -1

${CONTIGS}: ${R1}
	# Remove output directory if it already exists.
	[ -d $(dir $@) ] && rm -rf $(dir $@)

	# Perform sequence assembly with minia.
	${ENV_RUN} ${MINIA_CMD}

# Invoke minia command.
run: ${CONTIGS}
	ls -lh $(dir $^)

stats: ${CONTIGS}
	seqkit stats ${CONTIGS}
	
run!::
	rm -rf ${OUTDIR}

# Alternative target to run!
clean: run!

DEPS := minia seqkit
# Print command for installing dependencies.
install::
	micromamba create -n ${ENV}
	${ENV_RUN} micromamba install ${DEPS}

.PHONY: help run stats run! clean install
