#
# Assemble reads into contigs using SPAdes.
#

# Makefile preamble.
SHELL := bash
.DELETE_ON_ERROR:
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += --warn-undefined-variables --no-print-directory

# Micromamba environment.
ENV = bf-assembly-spades

# Run command within environment.
ENV_RUN = micromamba run -n ${ENV}

# Number of worker threads.
THREADS ?= 8

# Set memory allocation in Gb.
MEM ?= 8

# First of read pair.
R1 ?=

# Second of read pair. If not specified, perform assembly in SE mode.
R2 ?=

# Output directory.
OUTDIR ?= spades

# Target output.
CONTIGS = ${OUTDIR}/scaffolds.fasta

# Sequencing platform.
PLATFORM ?=

# K-mer size(s).
K ?= auto


help::
	@echo ""
	@echo "spades.mk: assemble reads into contigs using spades"
	@echo ""
	@echo "Usage:"
	@echo "  bf-spades R1=<R1> [options] <command>"
	@echo ""
	@echo "Commands:"
	@echo "  run            perform graph-based assembly with SPAdes"
	@echo "  assemble       alias for 'run'"
	@echo "  install        initialize conda environment"
	@echo "  clean          remove all output generated by this program"
	@echo ""
	@echo "Options:"
	@echo "  R1             first set of pair-end reads in FASTQ format (required)"
	@echo "  R2             second set of pair-end reads in FASTQ format"
	@echo "                 if not provided, program will run in single-end mode"
	@echo "  OUT            a directory path for storing megahit output (default: spades)"
	@echo "  K              k-mer size (default: auto)"
	@echo "  MEM            maximum memory allocation in Gb (default: 8)"
	@echo "  THREADS        number of compute threads (default: 8)"
	@echo ""

# R1 must exist.
${R1}:
	@echo "Error: R1 not found (R1=${R1})"
	@exit -1

# SPAdes options.
FLAGS := -t ${THREADS} -m ${MEM} -k ${K} --gfa11

# Compose megahit command.
ifeq (${R2},)
	SPADES_CMD = spades.py ${FLAGS} -s ${R1} -o ${OUTDIR}
else
	SPADES_CMD = spades.py ${FLAGS} -1 ${R1} -2 ${R2} -o ${OUTDIR}
endif

# If set, R2 must exist.
ifneq (${R2},)
${R2}:
	@echo "Error: R2 not found (R2=${R2})"
	@exit -1
endif

${CONTIGS}: ${R1} $(if ${R2}, ${R2})
	# Remove output directory if it already exists.
	[ -d $(dir $@) ] && rm -rf $(dir $@)

	# Run SPAdes assembly.
	${ENV_RUN} ${SPADES_CMD}

# Invoke SPAdes.
run: ${CONTIGS}
	ls -lh $(dir $^)

stats: ${CONTIGS}
	seqkit stats ${CONTIGS}
	
run!::
	rm -rf ${OUTDIR}

# Alternative target to run!
clean: run!

DEPS := spades seqkit
# Print command for installing dependencies.
install::
	micromamba create -n ${ENV}
	${ENV_RUN} micromamba install ${DEPS}

.PHONY: help run run! clean install
